import { createElement } from '@lwc/engine-dom';
import ComponentC from 'c/componentC';

describe('c-component-c', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-component-c', {
            is: ComponentC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    it('Check if the component is accessible', async () => {
        const element = createElement('c-component-c', {
            is: ComponentC
        });
        document.body.appendChild(element);
        await expect(element).toBeAccessible();
    });
});